plugin: openapi
specFile: ./private-api.yaml

validation:
  request: log

resources:

  - method: GET
    path: /authorization
    requestHeaders:
      session-id: good200
    response:
      statusCode: 200

  - method: GET
    path: /authorization
    requestHeaders:
      session-id: bad400
    response:
      statusCode: 400

  - method: GET
    path: /authorization
    requestHeaders:
      session-id: bad500
    response:
      statusCode: 500

  - method: POST
    path: /session
    requestBody:
      jsonPath: $.client_id
      value: ipv-toy-stub
    requestHeaders:
      X-Forwarded-For: b6372710-f401-11ed-a05b-0242ac120003
    response:
      statusCode: 201

  - method: POST
    path: /session
    response:
      statusCode: 400

  - method: POST
    path: /session
    requestBody:
      value: "invalid"
    response:
      statusCode: 500

  - method: POST
    path: /favourite
    requestHeaders:
      session-id: 1234565789
    requestBody:
      jsonPath: $.toy
      value: jigsaw-puzzle
    response:
      statusCode: 200

  - method: POST
    path: /favourite
    requestHeaders:
      session-id: 1234565789
    requestBody:
      jsonPath: $.toy
      value: pikachu
    response:
      statusCode: 404

  - method: POST
    path: /favourite
    requestHeaders:
      session-id: bad500
    response:
      statusCode: 500
