plugin: openapi
specFile: ./private-api.yaml

validation:
  request: log

resources:
  - method: POST
    path: /session
    requestBody:
      jsonPath: $.client_id
      value: "1fbc5730-9d17-416d-b2ca-0be90e1e93f5"
    response:
      statusCode: 201
      exampleName: 201

  - method: POST
    path: /session
    requestBody:
      jsonPath: $.client_id
      value: "fad21bea-bce9-4aa7-8889-d50c7d26616e"
    response:
      statusCode: 400
      exampleName: 400

  - method: POST
    path: /session
    requestBody:
      jsonPath: $.client_id
      value: "f27b8afc-90ef-4e0f-83ad-00a2f5692590"
    response:
      statusCode: 500
      exampleName: 500

  - method: POST
    path: /session
    response:
      statusCode: 500
      exampleName: 500

  - method: GET
    path: /authorization
    requestHeaders:
      session-id: "1fbc5730-9d17-416d-b2ca-0be90e1e93f5"
    response:
      statusCode: 200
      exampleName: 200

  - method: GET
    path: /authorization
    requestHeaders:
      session-id: "fad21bea-bce9-4aa7-8889-d50c7d26616e"
    response:
      statusCode: 400
      exampleName: 400

  - method: GET
    path: /authorization
    requestHeaders:
      session-id: "f27b8afc-90ef-4e0f-83ad-00a2f5692590"
    response:
      statusCode: 500
      exampleName: 500

  - method: GET
    path: /authorization
    response:
      statusCode: 500
      exampleName: 500

  - method: POST
    path: /favourite
    requestHeaders:
      session-id: "1fbc5730-9d17-416d-b2ca-0be90e1e93f5"
    requestBody:
      jsonPath: $.toy
      value: "jigsaw-puzzle"
    response:
      statusCode: 200

  - method: POST
    path: /favourite
    requestHeaders:
      session-id: "1fbc5730-9d17-416d-b2ca-0be90e1e93f5"
    requestBody:
      jsonPath: $.toy
      value: "tennis-bat"
    response:
      statusCode: 404

  - method: POST
    path: /favourite
    requestBody:
      jsonPath: $.toy
      value: "football"
    response:
      statusCode: 500

  - method: POST
    path: /favourite
    response:
      statusCode: 500
