plugin: openapi
specFile: ./private-api.yaml

validation:
  request: log

resources:

# --- Session start --- #

  - method: POST
    path: /session
    requestBody:
      jsonPath: $.client_id
      value: "scenario-1-happy"
    response:
      statusCode: 201
      exampleName: session-s1-good

  - method: POST
    path: /session
    requestBody:
      jsonPath: $.client_id
      value: "scenario-1-auth-400"
    response:
      statusCode: 201
      exampleName: session-s1-auth-400

  - method: POST
    path: /session
    requestBody:
      jsonPath: $.client_id
      value: "scenario-1-auth-500"
    response:
      statusCode: 201
      exampleName: session-s1-auth-500

  - method: POST
    path: /session
    requestBody:
      jsonPath: $.client_id
      value: "scenario-2"
    response:
      statusCode: 201
      exampleName: session-s2

  - method: POST
    path: /session
    requestBody:
      jsonPath: $.client_id
      value: "scenario-3"
    response:
      statusCode: 201
      exampleName: session-s3

  - method: POST
    path: /session
    requestBody:
      jsonPath: $.client_id
      value: "bad400"
    response:
      statusCode: 400

  - method: POST
    path: /session
    requestBody:
      jsonPath: $.client_id
      value: "bad500"
    response:
      statusCode: 500

  # --- Session end --- #

  # --- Auth start --- #

  - method: GET
    path: /authorization
    requestHeaders:
      session-id: "scenario-1"
    response:
      statusCode: 200
      exampleName: scenario-1

  - method: GET
    path: /authorization
    requestHeaders:
      session-id: "scenario-2"
    response:
      statusCode: 200
      exampleName: scenario-2

  - method: GET
    path: /authorization
    requestHeaders:
      session-id: "scenario-3"
    response:
      statusCode: 200
      exampleName: scenario-3

  - method: GET
    path: /authorization
    requestHeaders:
      session-id: "scenario-1-400"
    response:
      statusCode: 400

  - method: GET
    path: /authorization
    requestHeaders:
      session-id: "scenario-1-500"
    response:
      statusCode: 500

  # --- Auth end --- #

  # --- Favourite start --- #

  - method: POST
    path: /favourite
    requestHeaders:
      session-id: "success-path"
    requestBody:
      jsonPath: $.toy
      value: "jigsaw-puzzle"
    response:
      statusCode: 200

  - method: POST
    path: /favourite
    requestHeaders:
      session-id: "success-path"
    requestBody:
      jsonPath: $.toy
      value: "train-set"
    response:
      statusCode: 200

  - method: POST
    path: /favourite
    response:
      statusCode: 404

  - method: POST
    path: /favourite
    requestHeaders:
      session-id: bad500
    response:
      statusCode: 500

  # --- Favourite end --- #
