plugin: openapi
specFile: ./public-api.yaml

validation:
  request: log

resources:

  - method: POST
    path: /token
    formParams:
      code: bad400
    response:
      statusCode: 400

  - method: POST
    path: /token
    formParams:
      code: bad500
    response:
      statusCode: 500

  - method: POST
    path: /token
    response:
      statusCode: 201

  - method: POST
    path: /credential/issue
    requestHeaders:
      Authorization: Bearer 123456789
      application/jwt: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
    response:
      statusCode: 200

  - method: POST
    path: /credential/issue
    requestHeaders:
      Authorization: Bearer bad400
    response:
      statusCode: 400

  - method: POST
    path: /credential/issue
    requestHeaders:
      Authorization: Bearer bad500
    response:
      statusCode: 500
