plugin: openapi
specFile: ./public-api.yaml

validation:
  request: log

resources:

  - method: POST
    path: /token
    formParams:
      code: "981bb74c-3b5e-462e-ba3a-abf868e5da68"
      redirect_uri: "https://di-ipv-core-stub.london.cloudapps.digital/callback"
    response:
      statusCode: 201

  - method: POST
    path: /token
    formParams:
      code: bad400
    response:
      statusCode: 400

  - method: POST
    path: /token
    response:
      statusCode: 500

  - method: POST
    path: /credential/issue
    requestHeaders:
      Authorization: "Bearer d035dbfb-64a4-4cb6-940d-f0a3d0953363"
    response:
      statusCode: 200

  - method: POST
    path: /credential/issue
    requestHeaders:
      Authorization: Bearer bad400
    response:
      statusCode: 400

  - method: POST
    path: /credential/issue
    response:
      statusCode: 500
