plugin: openapi
specFile: ./public-api.yaml

validation:
  request: log

resources:

  - method: POST
    path: /token
    formParams:
      code: aaaaaaaaa
    response:
      statusCode: 400

  - method: POST
    path: /token
    formParams:
      code: null
    response:
      statusCode: 500

  - method: POST
    path: /token
    response:
      statusCode: 201

  - method: POST
    path: /credential/issue
    response:
      statusCode: 200

  - method: POST
    path: /credential/issue
    requestHeaders:
      SessionHeader: Authorization Bearer 123456789
      application/jwt: 123456789
    response:
      statusCode: 200

  - method: POST
    path: /credential/issue
    requestHeaders:
      SessionHeader: Authorization Bearer 0
    response:
      statusCode: 400

  - method: POST
    path: /credential/issue
    requestHeaders:
      SessionHeader: Authorization Bearer bad
    response:
      statusCode: 500
