plugin: openapi
specFile: ./public-api.yaml

validation:
  request: log

resources:

  - method: POST
    path: /token
    formParams:
      code: "scenario-1"
    response:
      statusCode: 201

  - method: POST
    path: /token
    formParams:
      code: "scenario-2"
    response:
      statusCode: 400

  - method: POST
    path: /token
    response:
      statusCode: 500

  - method: POST
    path: /credential/issue
    requestHeaders:
      Authorization: "Bearer scenario-1"
    response:
      statusCode: 200

  - method: POST
    path: /credential/issue
    requestHeaders:
      Authorization: "Bearer scenario-2"
    response:
      statusCode: 400

  - method: POST
    path: /credential/issue
    response:
      statusCode: 500
